name: Deploy Stage
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version Number'
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: avakar/create-deployment@v1
              name: Create GitHub deployment
              id: deployment
              with:
                  auto_merge: false
                  environment: stage
                  payload: "{\"version\": \"${{ github.event.inputs.version }}\"}"
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_DEPLOY_TOKEN }}

            - name: Print deployment url
              run: echo "${{ steps.deployment.outputs.deployment_url }}"
