name: Deploy Production
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version Number'
                required: true
env:
    GITHUB_TOKEN: ${{ secrets.REPO_DEPLOY_TOKEN }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: avakar/create-deployment@v1
              name: Create GitHub deployment
              id: deployment
              with:
                  auto_merge: false
                  environment: production
                  required_contexts: "build"
                  description: "Releasing ${{ github.ref }} as ${{ github.event.inputs.version }}"
                  payload: "{\"version\": \"${{ github.event.inputs.version }}\"}"

            - name: Print deployment url
              run: echo "${{ steps.deployment.outputs.deployment_url }}"
